name: aham_ai
description: "AhamAI - Your Intelligent Assistant"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  font_awesome_flutter: ^10.6.0
  flutter_highlight: ^0.7.0
  mime: ^1.0.4
  archive: ^4.0.7
  syncfusion_flutter_pdf: ^29.1.38
  xml: ^6.3.0
  file_picker: ^8.0.0+1
  flutter_markdown: ^0.7.3+1
  http: ^1.1.0
  image_picker: ^1.0.4
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.svg